services:
  PostgreSQL:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - PostgreSQL
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=pguser
      - --password=pgpwd
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data: